Added Fake script to build release version
MrCube42/Dashboard pull request #2
Opened 2016-10-20 15:29 UTC by Slesa

2016-10-20 17:51 UTC, devinmotion commented
Funktioniert schonmal! 👍

2016-10-20 18:00 UTC, MrCube42 requested changes
Could you please comment on (or fix) my findings

2016-10-20 18:00 UTC, devinmotion commented on build.cmd
> +if defined TEAMCITY_PROJECT_NAME goto Quit
Do we need this?

2016-10-20 18:00 UTC, devinmotion commented on build.cmd
> +rem Loop the build script.
Why should one loop the build script? It is meant to be run alongside developing?

2016-10-20 18:00 UTC, devinmotion commented on build.fsx
> +Log "Wotrking in ..." [ cwd ]
typo

2016-10-20 18:00 UTC, devinmotion commented on paket.lock
> +CONTENT: NONE
What exactly is this file good for? Does it tell the exact version ranges needed? What is the difference to packet.dependencies?

2016-10-20 19:21 UTC, Slesa commented on build.cmd
> +if defined TEAMCITY_PROJECT_NAME goto Quit
Depends on the build server this file will build on. Or if we keep the loop at all.

2016-10-20 19:22 UTC, Slesa commented on build.cmd
> +rem Loop the build script.
It is very helpful when you change the build.fsx. You simply hit enter. Additional, the build script will not try to resolve paket.exe again and again.

2016-10-20 19:24 UTC, Slesa commented on paket.lock
> +CONTENT: NONE
It is the corresponding file for the paket.dependency. "paket install" will create it, but the build script assumes this already has been done.

2016-10-20 19:24 UTC, Slesa commented on build.fsx
> +Log "Wotrking in ..." [ cwd ]
Both lines have to be removed. Was debugging.

2016-10-21 16:22 UTC, MrCube42 approved these changes

2016-10-21 16:22 UTC, merged